### ISSUE TITLE
Build - Prevent all keys required at all times

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/news#115]
See: https://github.com/freeCodeCamp/news/runs/4669071805?check_suite_focus=true#step:5:48, this build was specifically for English but it needed all the other keys to be defined.

**Comment by scissorsneedfoodtoo** [comment]
Unfortunately I don't think we'll be able to do this with the upcoming author / translator feature, at least not without some possible slowdown during the build process.

Since all the current translated articles in the non-English Ghost instances are from English-another language, it would be possible just to have English API keys for every build (English, Chinese, Spanish, etc.). Then while the site is being built, we can query the English API for the original author and some other data.

But we decided a while back that the feature should work both ways, so if an original article in Spanish is translated to English, we can grab data from the Espanol API during the build process.

The current code, while messy and rather hacky, assumes this, and needs all the keys to be defined.

An alternative would be to use something like Node Fetch and an HTML parser to get the data we need from the original article instead of the APIs. This should be possible, but may be slower and a bit trickier than using the API itself.

I'm fine with either method, though I do prefer the API method if possible. We may run into some caching or rate limiting issues if we fetch live articles during the build.

Or another thing we can do is disable this feature for the time being, and roll it out a bit later once the copy, translations, and design have been reviewed.

**Comment by raisedadead** [comment]
Thanks for the clarification, we do not need to overcomplicate things. I was more concerned about setting up unnecessary keys. But looks like these are (or will be) used. 

Closing.

**Comment by scissorsneedfoodtoo** [comment]
No problem, and thanks for pointing this out. It's a good reminder to actually finish that feature :)
