### ISSUE TITLE
Audit the RTL layout with the Arabic articles

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/news#198]
@islamh-mahfouz, I was wondering if you could kindly audit the RTL layout with the Arabic articles and create an umbrella issue so we could address all of the inconsistencies together.

Here is what we have came across so far:
- The word break issue explained above.
- Twitter button tweets left to right titles.

_Originally posted by @ahmadabdolsaheb in https://github.com/freeCodeCamp/news/issues/194#issuecomment-1044378083_

**Comment by raisedadead** [comment]
> @ahmadabdolsaheb i've audited the articles and the only thing i could find other than what has been already mentioned, is the wrong alignment of text in one specific article
> 
> the arabic version : [freecodecamp.org/arabic/news/laab-mtsfh-google-lbysbwl-wbkmn-wlmzyd](https://www.freecodecamp.org/arabic/news/laab-mtsfh-google-lbysbwl-wbkmn-wlmzyd/)
> 
> the english version: [freecodecamp.org/news/google-doodle-games-baseball-pacman-and-more](https://www.freecodecamp.org/news/google-doodle-games-baseball-pacman-and-more/)
> 
> <img alt="Screen Shot 2022-02-21 at 8 01 39 PM" width="1676" src="https://user-images.githubusercontent.com/99178533/155007113-4f0a5822-77c8-4656-9bde-9a5de67a6e42.png">
> 
> <img alt="Screen Shot 2022-02-21 at 8 01 59 PM" width="1680" src="https://user-images.githubusercontent.com/99178533/155007185-58b463fb-f32e-4c10-8f96-cb3dee471939.png">

_Originally posted by @islamh-mahfouz in https://github.com/freeCodeCamp/news/pull/194#issuecomment-1047124354_

**Comment by scissorsneedfoodtoo** [comment]
@raisedadead, I believe the problem in the articles you linked to above are due to the Arabic versions being written in markdown. There's no line break between some of the text and images, causing the images to be nested within the paragraphs and stretching the text out past the main container.

I'll go in and fix that now. There may be some instances in other articles, but they'll need to be fixed in the Ghost editor.

**Comment by ahmaxed** [comment]
@scissorsneedfoodtoo, did not have much luck with changing the `overflow-wrap: break-word` for the word break, but the following should resolve the issue:
```
.rtl-layout .post-full-content p code {
    word-break: break-word; 
}
```

**Comment by ahmaxed** [comment]
There does not seem to be straight forward way to add text direction to our twitter intent button implementation.
https://stackoverflow.com/questions/71253314/how-to-create-a-rtl-right-to-left-tweet-button

I will look further into parsing the title string and reordering.

Meanwhile, I think we can move forward publicizing the Arabic publication since the twitter button does not seem to be a blocker.

**Comment by islamh-mahfouz** [comment]
thank you all very much for your efforts ! i will publicize this tomorrow through twitter :)

**Comment by scissorsneedfoodtoo** [comment]
> @scissorsneedfoodtoo, did not have much luck with changing the `overflow-wrap: break-word` for the word break, but the following should resolve the issue:
> 
> ```
> .rtl-layout .post-full-content p code {
>     word-break: break-word; 
> }
> ```

Awesome, thanks for digging into this. You're right, `overflow-wrap: break-word` doesn't appear to work there. I'll take a look at your PR now.

**Comment by X7md** [comment]
Can add force `dir="ltr"` attr with `<code>` snippet to fix inline code?:

![image](https://user-images.githubusercontent.com/54203033/155748048-ef508cf9-eda4-4dde-a367-76a9056cd478.png)

I already do that in my blog and I made rehype plug-in to add it when I parsing my markdown file.
https://github.com/X7md/rehype-code-ltr

**Comment by X7md** [comment]
> text direction to our twitter int

What about add Arabic word at first of the tweet, something like:
```js
let textTweet = `JSON Stringify - كيفية تحليل كائن JSON باستخدام JS \n\n https://www.freecodecamp.org/arabic/news/json-sstr-kyfy-thlyl-kyn-json-bstkhdm-js/`

// add مقالة: at first before the title.
let twitterWebIntent = "https://twitter.com/intent/tweet?text=" +encodeURIComponent("مقالة: " + textTweet);
```

![image](https://user-images.githubusercontent.com/54203033/155751313-a072f057-2f31-47fe-b723-c534c84ef2e6.png)

**Comment by X7md** [comment]
Preview:

[مشاركة المقالة على تغريدة ](https://twitter.com/intent/tweet?text=%D9%85%D9%82%D8%A7%D9%84%D8%A9%3A%20JSON%20Stringify%20-%20%D9%83%D9%8A%D9%81%D9%8A%D8%A9%20%D8%AA%D8%AD%D9%84%D9%8A%D9%84%20%D9%83%D8%A7%D8%A6%D9%86%20JSON%20%D8%A8%D8%A7%D8%B3%D8%AA%D8%AE%D8%AF%D8%A7%D9%85%20JS%20%0A%0A%20https%3A%2F%2Fwww.freecodecamp.org%2Farabic%2Fnews%2Fjson-sstr-kyfy-thlyl-kyn-json-bstkhdm-js%2F)

**Comment by X7md** [comment]
> Can add force `dir="ltr"` attr with `<code>` snippet to fix inline code?:
> 
> ![image](https://user-images.githubusercontent.com/54203033/155748048-ef508cf9-eda4-4dde-a367-76a9056cd478.png)
> 
> I already do that in my blog and I made rehype plug-in to add it when I parsing my markdown file. https://github.com/X7md/rehype-code-ltr

Fix inline Code Snippet direction by CSS.

PR: #206

**Comment by ahmaxed** [comment]
@X7md, thanks for looking into this issue. 

@islamh-mahfouz, the initial text seems altered as @scissorsneedfoodtoo mentioned in a[ related discussion](https://github.com/freeCodeCamp/news/pull/194#issuecomment-1044138230). 

Could you check if it needs to be changed to its original direction or not?

If that is the case, we should prioritize auditing articles for inconsistencies. Then we could look into styling.

**Comment by islamh-mahfouz** [comment]
@ahmadabdolsaheb i will get to the bottom of this 👍

**Comment by islamh-mahfouz** [comment]
@ahmadabdolsaheb  @scissorsneedfoodtoo  after digging into this, the problem seems to be related to `dir="ltr"` being applied to code blocks which are wrapped in `pre` tags, but not being applied to `inline code` that is contained within arabic text wrapped in just  `p` tags (or other tags like headings), being displayed in `rtl`. 

as for the snippets shared above by **X7md**, this just needs manual editing on ghost from my side.

below are illustration

you can see here that code blocks in `pre` are displayed correctly with direction `ltr`
<img width="1673" alt="pre-code" src="https://user-images.githubusercontent.com/99178533/158578227-0d747d0b-d55f-4bb2-90f2-15840d97abef.png">

however, here as you can see, although the `inline code` is written correctly, it is not displayed correctly because its within `rtl` arabic text
<img width="1678" alt="before" src="https://user-images.githubusercontent.com/99178533/158578422-4fdf7dae-5a27-44a8-a655-d1771918189c.png">

and here after applying `dir="ltr"`, it gets displayed correctly.
<img width="1674" alt="after" src="https://user-images.githubusercontent.com/99178533/158578624-f9a42e0d-1e17-4bb3-a8d5-ed3fd7c732a6.png">

**Comment by islamh-mahfouz** [comment]
there is also an issue with `inline code breaking` as such

<img width="1670" alt="before" src="https://user-images.githubusercontent.com/99178533/158585524-da466c7e-a5d4-4030-a2aa-9251f5ec1d5c.png">

which i believe can be fixed by adding `white-space: nowrap`

<img width="1675" alt="after" src="https://user-images.githubusercontent.com/99178533/158585591-b48aeded-6d87-448d-8b50-deb8e3d8100c.png">

**Comment by islamh-mahfouz** [comment]
i have reviewed all the published articles and edited the inconsistencies regarding inline code within `paragraph` or `heading` tags and `line breaks` around `images`, took about 5 hours to review and edit all articles, but now with applying the above mentioned fixes, all should be good and consistent

**Comment by scissorsneedfoodtoo** [comment]
Wow, thank you for your thorough investigation and for fixing all of those articles, @islamh-mahfouz. All of your findings will help not only the Arabic publication, but any future publications that also use the RTL layout.

Also, thank you for that method of fixing the layout for RTL Twitter messages, @X7md. Adding a bit of RTL text to the beginning of each Tweet seems to fix the issue, and sets the text layout direction for the rest of the text in the web intent window.

**Comment by raisedadead** [comment]
Is this still an issue?

**Comment by ahmaxed** [comment]
The twitter card issue still persists. @scissorsneedfoodtoo, @X7md suggested should I put together a translation list of the word `article:` and and add it to the beginning of RTL twitter cards?

**Comment by scissorsneedfoodtoo** [comment]
Thanks for the reminder about this. I worked pretty closely with Zaira on the Urdu publication on this, and part of the tweet thanking authors and translators render from right to left correctly.

But the line with the article title itself sometimes renders from LTR if the title starts with a non-RTL character.

Starting all of those lines with `article: ` would be a good way around that.

It's probably best to handle this in the `translation.json` files. We could have an entry in `social-row.tweets` named `title-layout` or something similar:

```
...
    "tweets": {
      "default": "Thank you {{ author }} for writing this helpful article.",
      "translation": "Thank you {{ author }} for writing this helpful article, and {{ translator }} for translating it."
      "title-layout": "{{ title }}",
    }
...
```

This would give us fine-grained control for each publication, and we could do something like `"title-layout": "مضمون: {{ title }}"` for each RTL language.

I don't think that snippet is exactly right for Urdu, but we can get help from the individual editors.

**Comment by X7md** [comment]
I found this lib https://github.com/wooorm/direction, I think it's maybe will be helpful to detect `RTL/LTR` so can chose if its need to add workaround for RTL or not...

Demo:
https://wooorm.com/direction/

**Comment by zairahira** [comment]
There are a few hashtag alignment issues in Arabic and Urdu news as shown in the images below:

![image](https://user-images.githubusercontent.com/33151350/196654366-39134b01-610d-451a-b86b-af45188a4348.png)


![image](https://user-images.githubusercontent.com/33151350/196654023-e61ae56d-7c1d-47c2-b438-824961098c8e.png)

**Comment by raisedadead** [comment]
Please open fresh issues (independent) if any for RTL.
