### ISSUE TITLE
search placeholder should not pass through crowdin

### ISSUE THREAD

**Issue by majestic-owl448** [freeCodeCamp/news#444]
> I think it might be better to close this string and fix it on Crowdin for the next sync action.
> 
> The English string was update recently to "Search 9,000+ tutorials", but it should read "Buscar entre os mais de 300 tutoriais" or even "Buscar entre os mais de 350 tutoriais" in Portuguese.
> 
> Do you know what might have happened here @naomi-lgbt?
> 
> Also, it might be worth moving the search related strings into a separate file so it's clear that each publication should change the placeholder based on the number of articles they've published.

_Originally posted by @scissorsneedfoodtoo in https://github.com/freeCodeCamp/news/issues/441#issuecomment-1261746170_

**Comment by naomi-lgbt** [comment]
I discussed this with @scissorsneedfoodtoo in a meeting last night, and have proposed this implementation:

- Pull the numbers out into a separate config object, so we can set a number for each language directly.
- Update the existing translation string to interpolate the number as a variable.
- Add logic that checks if the number is 0, if so display a new "Search articles" translation string instead of the existing interpolation.

**Comment by majestic-owl448** [comment]
Is any of you two going to work on this specifically? or is this for anyone to take?

**Comment by naomi-lgbt** [comment]
I think Kris was spiking on it.
