### ISSUE TITLE
Remove redundant author/translator’s name

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/news#519]
Can we remove the duplicate author/translator’s name at the beginning of the article? (The part I marked yellow in the image below) 
It seems redundant, especially on mobile layout since there is no cover image displayed.

We can keep the original article's title.

![image](https://user-images.githubusercontent.com/25644062/208443657-6db2526e-30e9-4bab-bcd8-ba9ada025f4a.png)

**To Reproduce**
1. Open a translated article such as: https://www.freecodecamp.org/japanese/news/freecodecamp-2022-top-contributors/

**Additional context**
I proposed this in the i18n team meeting and we agreed on removing it.

**Comment by sidemt** [comment]
@scissorsneedfoodtoo I'm assuming the relevant code is around here:
https://github.com/freeCodeCamp/news/blob/d6acd7d4130d827b039de2f50e5c04080794aee1/utils/ghost/original-post-handler.js#L60

If it's not something too complicated, I will try working on this.

**Comment by scissorsneedfoodtoo** [comment]
Hi @sidemt, thank you for this suggestion and for creating an issue for this.

Sure! Feel free to work on this.

And yes, that file contains most of the code that'll need to change. The end of that file can be simplified quite a bit since the `introEl` just needs the first `span` element now.

Also, `authorEl` can probably be renamed to something more appropriate like `originalArticleTitle`, or something along those lines.

We could also look at updating this object in the English `translation.json` file: https://github.com/freeCodeCamp/news/blob/188352a7fce012e5f763eac1c99d02c9369999a6/config/i18n/locales/english/translations.json#L53-L56

Instead of an object it could just be a string with `"{{ <0> }}Original article:{{ </0> }} {{ title }}"`.

I can send you the keys you'll need to develop locally with the Dockerized Ghost instances over Signal. And thanks again for your help here.
