### ISSUE TITLE
Syntax highlighting breaks when visiting publication from Google

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/news#602]
### Describe the Issue

When visiting a publication tutorial from Google, syntax highlighting will not immediately show up. Only upon refreshing will the syntax highlighting show up.

### Affected Page

All publication tutorials tested, including this one: https://www.freecodecamp.org/news/append-a-string-in-python-str-appending/

### Steps to Reproduce

1. Go to a publication tutorial from Google search, using its URL such as https://www.freecodecamp.org/news/append-a-string-in-python-str-appending/
2. Scroll down to a code snippet. It will initially not have syntax highlighting.
3. Hit control+r to refresh the page. Boom, the syntax highlighting will now show up like it is supposed to.

### Expected behavior

Syntax highlighting is important, and we want it to show up correctly the first time without a refresh.

### Screenshots

![Cursor_and_Append_a_String_in_Python_–_STR_Appending](https://user-images.githubusercontent.com/985197/228365246-acb799f9-5a5d-48fb-a236-3d117ed05293.png)

![Cursor_and_Append_a_String_in_Python_–_STR_Appending](https://user-images.githubusercontent.com/985197/228365325-ba8b698c-c69e-4cf5-8ec8-394905b87340.png)

### System

- Device: Mac
- OS: MacOS latest
- Browser: Chrome
- Version: Version 111.0.5563.110

**Comment by Mikadifo** [comment]
I followed the steps to reproduce it and I had the same problem just inverted. The first time I open the page it does have syntax highlighting and after refreshing the page with cmd+shift+r, the syntax highlighting disappears.

I also tried copying the link to another tab and browser and then it happened as you said. If I click the link it works fine at first.

**Comment by Sboonny** [comment]
This issue seems similar to RTL not applying its classes in this issue #538, I have assigned kris to bring it to his attention.

**Comment by scissorsneedfoodtoo** [comment]
Thanks for reporting this, @QuincyLarson, and for those helpful details @Mikadifo and @Sboonny.

I was able to reproduce the issues that Quincy and @Mikadifo described above.

I believe we're getting these issues because we defer the main Prism.js script, and the scripts to add syntax highlighting in other languages. Normally the Prism scripts wait for the page to load completely before running. But deferring the script(s) can cause issues, at least for older versions like v1.16.0 which we're currently using.

This issue was fixed somewhere between v1.16.0 and the latest version, v1.29.0. It seems like the easiest fix would be to upgrade to the latest version of Prism. This will also give us the chance to use the autoloader plugin to dynamically load the correct syntax highlighting scripts for each article, without including them all like we're currently doing, or doing that during page builds.

I did some testing locally with Prism v1.29.0 and syntax highlighting is applied every time I do a hard refresh of the page. It should also fix the issue of syntax highlighting not being applied when navigating to an article from Google.
