### ISSUE TITLE
Clean up registry for items older than 2 days on DigitalOcean

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/news#705]
ref #704

**Comment by naomi-lgbt** [comment]
Gonna drop some research/brainstorming here:

> [!NOTE]
> There doesn't seem to be a way to delete a specific image through the API. Only through the control panel.

1. We can use `doctl registry repository list-tags` to get the list of tags in the repository.

This gives us a list of tags, including the tag name and the `Updated At` timestamp.

2. We can iterate through the tags to find tags that were last updated over two days ago.

3. We can pass each tag to `doctl registry repository delete-tag`.

4. Finally, we can trigger a garbage collection run with `doctl registry garbage-collection start`. Passing the `--include-untagged-manifests` flag *should* mean that the images associated with the deleted tags are cleaned up (if I am understanding correctly) because they no longer have any tags.

**Comment by raisedadead** [comment]
Yep - that's what I was thinking.
