### ISSUE TITLE
Broken publication article: iframe embedded content covers post body

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/news#967]
**Describe the bug**
There is a forum post reporting that a publication article is broken. I could reproduce the problem on my end.
https://forum.freecodecamp.org/t/cant-read-article-on-website-due-to-gray-rectangle/707631

From what I can see in the DevTools, the issue seems to be caused by the <iframe> element that appears to be an embedded content from Canva.

I'm not sure if this is related to the Hashnode migration.

**To Reproduce**
1. Go to https://www.freecodecamp.org/news/singleton-design-pattern-with-javascript/
2. Scroll down the page

**Expected behavior**
The article should be visible and laid out properly.

**Screenshots**
![image (4)](https://github.com/user-attachments/assets/b65794ad-a730-4549-9686-013ad8df86d0)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version: 127.0.6533.120

**Comment by raisedadead** [comment]
> I'm not sure if this is related to the Hashnode migration.

Yes this author has been moved to Hashnode and I believe there is no support for embeds involving iframe because it is a security issue. 

Most likely solution should be to get the article edited and have a simple link and then generate an embed ourselves in the SSG - which also needs a feasibility check.

**Comment by raisedadead** [comment]
See https://support.hashnode.com/en/articles/6423225-markdown-guidelines#h_01a920df32 so we have to get an equivalent with this https://embed.ly/provider/canva. More providers are here https://embed.ly/providers

**Comment by ihechikara** [comment]
Hi @raisedadead @sidemt, this issue has been resolved. Although [Hashnode supports embeds from CodeSandbox](https://support.hashnode.com/en/articles/6435289-which-embeds-are-supported-by-hashnode), we had this issue because the format that generates an iframe was used.

I used the option that generates an embed URL instead: https://codesandbox.io/embed/zqbo69?view=editor+%2B+preview

### Screenshots

**Embed options on CodeSandbox**

![image](https://github.com/user-attachments/assets/070d28ea-4847-46c2-bfa0-6c4fc8819dc6)

**Embed on [/news](https://www.freecodecamp.org/news/singleton-design-pattern-with-javascript/)**

![image](https://github.com/user-attachments/assets/dc233ef3-69e9-4dda-aeb0-16814c1a1848)

**The article is now visible and laid out properly**

![image](https://github.com/user-attachments/assets/c1dfe15a-2b6f-4484-bddf-efac273d2e1a)

**Comment by raisedadead** [comment]
Thanks @ihechikara !
